### ISSUE TITLE
As a user, I want to be able to create an account and log in to the application. 

### ISSUE THREAD

**Issue by higgins-j** [just1higg/WheresMyStuff#2]

**Comment by skipkayhil** [comment]
M4 checklist:
- [x] Given welcome screen, When a user clicks login, then user is taken to login screen
- [x] Given welcome screen, When a user clicks sign up, then user is taken to sign up screen
---
- [x] Given Login screen, When a user clicks login, then credentials are checked
- [x] Given credentials, When they are correct, then user is taken to App
- [x] Given credentials, When they are incorrect, then error is shown
---
- [x] Given Sign Up screen, When a user clicks sign up, then credentials are checked
- [x] Given credentials, When they fit requirements, then user is signed in and taken to App
- [x] Given credentials, When they don't fit requirements or email is in use, then error is shown
---
- [x] Given app, When user clicks logout, user is logged out and taken to welcome screen

**Comment by higgins-j** [comment]
With the completion of M4, this issue is nearly complete. We are still integrating Firebase into the application for password storage and authentication.
